# Generated by Django 5.2.3 on 2025-06-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('consumed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
