# Generated by Django 5.2.3 on 2025-08-15 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_consumedevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsumedEvent',
        ),
    ]
